name: TalkAi CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - run: yarn build
      - run: yarn test

  merge-check:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Merge Check
        run: |
          if [ "${{ needs.build-and-test.outcome }}" == "failure" ]; then
            echo "CI Build and Test failed. Aborting merge."
            exit 1
          else
            echo "CI Build and Test passed. Ready for merge."
          fi
